"""Generate delivery copies only; never overwrite originals or change framing.

Requires Pillow. Run from any directory: python scripts/optimize-images.py
The generated TypeScript maps keep home/specialty asset data in separate chunks.
"""
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'src/assets'
GROUPS = {
    'home': [
        'about/reception.png', 'about/mosaic-mark.png',
        'photography/clinic-body-care.jpg', 'photography/facial-lip-treatment.jpg',
        'photography/kelly-treatment-room.jpg',
        *[str(p.relative_to(ASSETS)).replace('\\', '/') for p in (ASSETS / 'professionals').glob('*.webp')],
    ],
    'specialty': [
        'hero/harmonization-body-result-sem-data.webp', 'hero/harmonization-body-male.webp',
        'hero/weight-loss-front.jpg', 'hero/weight-loss-side.jpg',
        'treatments/phaloplasty-consultation-candid.jpg', 'treatments/phaloplasty-private-care.webp',
        'treatments/weight-loss-multiprofessional-evaluation.jpg', 'treatments/weight-loss.jpg',
        'photography/harmonization-body-application.jpg',
        *[str(p.relative_to(ASSETS)).replace('\\', '/') for p in (ASSETS / 'results').glob('*.webp')],
        'results/result-10.jpg', 'results/result-12.jpg',
    ],
}
out = ASSETS / 'optimized'
out.mkdir(exist_ok=True)
for group, paths in GROUPS.items():
    imports = ["// Generated by scripts/optimize-images.py; delivery copies preserve the original framing.",
               "import { createImageProps } from '../utils/responsiveImage'"]
    entries = []
    for index, relative in enumerate(dict.fromkeys(paths)):
        original = ASSETS / relative
        with Image.open(original) as source:
            image = ImageOps.exif_transpose(source)
            # Retain transparent ornaments; dropping alpha would create a solid box.
            image = image.convert('RGBA' if 'A' in image.getbands() or 'transparency' in image.info else 'RGB')
            width, height = image.size
            max_width = min(width, 1200 if group == 'specialty' else 960)
            widths = sorted(set([size for size in [320, 640, 960] if size < max_width] + [max_width]))
            # Clinical comparisons use a higher quality level; no crop, filters or retouching.
            quality = 90 if 'result' in relative or 'facial-' in relative or 'body-male' in relative else 84
            imports.append(f"import original{index} from '../assets/{relative}'")
            variants = []
            for size in widths:
                name = f"{original.stem}-{size}.webp"
                resized = image.resize((size, round(height * size / width)), Image.Resampling.LANCZOS)
                resized.save(out / name, 'WEBP', quality=quality, method=6)
                variable = f'image{index}_{size}'
                imports.append(f"import {variable} from '../assets/optimized/{name}'")
                variants.append((variable, size))
            default = variants[-1][0]
            srcset = ', '.join('${' + variable + '} ' + str(size) + 'w' for variable, size in variants)
            entries.append(f'  [original{index}]: {{ src: {default}, srcSet: `{srcset}`, width: {width}, height: {height} }},')
    code = '\n'.join(imports) + '\n\nexport const ' + group + 'ImageProps = createImageProps({\n' + '\n'.join(entries) + '\n})\n'
    (ROOT / f'src/data/{group}ImageVariants.ts').write_text(code, encoding='utf-8')
    print(f'{group}: {len(entries)} sources, optimized copies generated')
