// Generated by scripts/optimize-images.py; delivery copies preserve the original framing.
import { createImageProps } from '../utils/responsiveImage'
import original0 from '../assets/about/reception.png'
import image0_320 from '../assets/optimized/reception-320.webp'
import image0_640 from '../assets/optimized/reception-640.webp'
import image0_900 from '../assets/optimized/reception-900.webp'
import original1 from '../assets/about/mosaic-mark.png'
import image1_138 from '../assets/optimized/mosaic-mark-138.webp'
import original2 from '../assets/photography/clinic-body-care.jpg'
import image2_320 from '../assets/optimized/clinic-body-care-320.webp'
import image2_640 from '../assets/optimized/clinic-body-care-640.webp'
import image2_960 from '../assets/optimized/clinic-body-care-960.webp'
import original3 from '../assets/photography/facial-lip-treatment.jpg'
import image3_320 from '../assets/optimized/facial-lip-treatment-320.webp'
import image3_640 from '../assets/optimized/facial-lip-treatment-640.webp'
import image3_960 from '../assets/optimized/facial-lip-treatment-960.webp'
import original4 from '../assets/photography/kelly-treatment-room.jpg'
import image4_320 from '../assets/optimized/kelly-treatment-room-320.webp'
import image4_640 from '../assets/optimized/kelly-treatment-room-640.webp'
import image4_960 from '../assets/optimized/kelly-treatment-room-960.webp'
import original5 from '../assets/professionals/diego-lacerda.webp'
import image5_320 from '../assets/optimized/diego-lacerda-320.webp'
import image5_540 from '../assets/optimized/diego-lacerda-540.webp'
import original6 from '../assets/professionals/diogo-rafael.webp'
import image6_320 from '../assets/optimized/diogo-rafael-320.webp'
import image6_640 from '../assets/optimized/diogo-rafael-640.webp'
import image6_960 from '../assets/optimized/diogo-rafael-960.webp'
import original7 from '../assets/professionals/fernanda-lucas.webp'
import image7_320 from '../assets/optimized/fernanda-lucas-320.webp'
import image7_640 from '../assets/optimized/fernanda-lucas-640.webp'
import image7_960 from '../assets/optimized/fernanda-lucas-960.webp'
import original8 from '../assets/professionals/kelly-trindade.webp'
import image8_320 from '../assets/optimized/kelly-trindade-320.webp'
import image8_640 from '../assets/optimized/kelly-trindade-640.webp'
import image8_960 from '../assets/optimized/kelly-trindade-960.webp'
import original9 from '../assets/professionals/yeiko-faloplastia.webp'
import image9_320 from '../assets/optimized/yeiko-faloplastia-320.webp'
import image9_640 from '../assets/optimized/yeiko-faloplastia-640.webp'
import original10 from '../assets/professionals/yeiko-roca.webp'
import image10_320 from '../assets/optimized/yeiko-roca-320.webp'
import image10_640 from '../assets/optimized/yeiko-roca-640.webp'
import image10_960 from '../assets/optimized/yeiko-roca-960.webp'

export const homeImageProps = createImageProps({
  [original0]: { src: image0_900, srcSet: `${image0_320} 320w, ${image0_640} 640w, ${image0_900} 900w`, width: 900, height: 1200 },
  [original1]: { src: image1_138, srcSet: `${image1_138} 138w`, width: 138, height: 175 },
  [original2]: { src: image2_960, srcSet: `${image2_320} 320w, ${image2_640} 640w, ${image2_960} 960w`, width: 1000, height: 1333 },
  [original3]: { src: image3_960, srcSet: `${image3_320} 320w, ${image3_640} 640w, ${image3_960} 960w`, width: 1000, height: 1000 },
  [original4]: { src: image4_960, srcSet: `${image4_320} 320w, ${image4_640} 640w, ${image4_960} 960w`, width: 1200, height: 1800 },
  [original5]: { src: image5_540, srcSet: `${image5_320} 320w, ${image5_540} 540w`, width: 540, height: 720 },
  [original6]: { src: image6_960, srcSet: `${image6_320} 320w, ${image6_640} 640w, ${image6_960} 960w`, width: 960, height: 1280 },
  [original7]: { src: image7_960, srcSet: `${image7_320} 320w, ${image7_640} 640w, ${image7_960} 960w`, width: 960, height: 1280 },
  [original8]: { src: image8_960, srcSet: `${image8_320} 320w, ${image8_640} 640w, ${image8_960} 960w`, width: 960, height: 1280 },
  [original9]: { src: image9_640, srcSet: `${image9_320} 320w, ${image9_640} 640w`, width: 640, height: 960 },
  [original10]: { src: image10_960, srcSet: `${image10_320} 320w, ${image10_640} 640w, ${image10_960} 960w`, width: 960, height: 1280 },
})
