// Generated by scripts/optimize-images.py; delivery copies preserve the original framing.
import { createImageProps } from '../utils/responsiveImage'
import original0 from '../assets/hero/harmonization-body-result-sem-data.webp'
import image0_320 from '../assets/optimized/harmonization-body-result-sem-data-320.webp'
import image0_640 from '../assets/optimized/harmonization-body-result-sem-data-640.webp'
import image0_960 from '../assets/optimized/harmonization-body-result-sem-data-960.webp'
import image0_1200 from '../assets/optimized/harmonization-body-result-sem-data-1200.webp'
import original1 from '../assets/hero/harmonization-body-male.webp'
import image1_320 from '../assets/optimized/harmonization-body-male-320.webp'
import image1_640 from '../assets/optimized/harmonization-body-male-640.webp'
import image1_960 from '../assets/optimized/harmonization-body-male-960.webp'
import image1_1100 from '../assets/optimized/harmonization-body-male-1100.webp'
import original2 from '../assets/hero/weight-loss-front.jpg'
import image2_320 from '../assets/optimized/weight-loss-front-320.webp'
import image2_640 from '../assets/optimized/weight-loss-front-640.webp'
import image2_960 from '../assets/optimized/weight-loss-front-960.webp'
import image2_1200 from '../assets/optimized/weight-loss-front-1200.webp'
import original3 from '../assets/hero/weight-loss-side.jpg'
import image3_320 from '../assets/optimized/weight-loss-side-320.webp'
import image3_640 from '../assets/optimized/weight-loss-side-640.webp'
import image3_960 from '../assets/optimized/weight-loss-side-960.webp'
import image3_1200 from '../assets/optimized/weight-loss-side-1200.webp'
import original4 from '../assets/treatments/phaloplasty-consultation-candid.jpg'
import image4_320 from '../assets/optimized/phaloplasty-consultation-candid-320.webp'
import image4_640 from '../assets/optimized/phaloplasty-consultation-candid-640.webp'
import image4_960 from '../assets/optimized/phaloplasty-consultation-candid-960.webp'
import image4_1200 from '../assets/optimized/phaloplasty-consultation-candid-1200.webp'
import original5 from '../assets/treatments/phaloplasty-private-care.webp'
import image5_320 from '../assets/optimized/phaloplasty-private-care-320.webp'
import image5_640 from '../assets/optimized/phaloplasty-private-care-640.webp'
import image5_960 from '../assets/optimized/phaloplasty-private-care-960.webp'
import original6 from '../assets/treatments/weight-loss-multiprofessional-evaluation.jpg'
import image6_320 from '../assets/optimized/weight-loss-multiprofessional-evaluation-320.webp'
import image6_640 from '../assets/optimized/weight-loss-multiprofessional-evaluation-640.webp'
import image6_853 from '../assets/optimized/weight-loss-multiprofessional-evaluation-853.webp'
import original7 from '../assets/treatments/weight-loss.jpg'
import image7_320 from '../assets/optimized/weight-loss-320.webp'
import image7_640 from '../assets/optimized/weight-loss-640.webp'
import image7_960 from '../assets/optimized/weight-loss-960.webp'
import image7_1200 from '../assets/optimized/weight-loss-1200.webp'
import original8 from '../assets/photography/harmonization-body-application.jpg'
import image8_320 from '../assets/optimized/harmonization-body-application-320.webp'
import image8_640 from '../assets/optimized/harmonization-body-application-640.webp'
import image8_960 from '../assets/optimized/harmonization-body-application-960.webp'
import image8_1200 from '../assets/optimized/harmonization-body-application-1200.webp'
import original9 from '../assets/results/facial-female-front-7360.webp'
import image9_320 from '../assets/optimized/facial-female-front-7360-320.webp'
import image9_640 from '../assets/optimized/facial-female-front-7360-640.webp'
import image9_960 from '../assets/optimized/facial-female-front-7360-960.webp'
import image9_1200 from '../assets/optimized/facial-female-front-7360-1200.webp'
import original10 from '../assets/results/facial-female-front-8121.webp'
import image10_320 from '../assets/optimized/facial-female-front-8121-320.webp'
import image10_640 from '../assets/optimized/facial-female-front-8121-640.webp'
import image10_960 from '../assets/optimized/facial-female-front-8121-960.webp'
import image10_1200 from '../assets/optimized/facial-female-front-8121-1200.webp'
import original11 from '../assets/results/facial-female-profile-8122.webp'
import image11_320 from '../assets/optimized/facial-female-profile-8122-320.webp'
import image11_640 from '../assets/optimized/facial-female-profile-8122-640.webp'
import image11_960 from '../assets/optimized/facial-female-profile-8122-960.webp'
import image11_1200 from '../assets/optimized/facial-female-profile-8122-1200.webp'
import original12 from '../assets/results/facial-female-three-quarter-8437.webp'
import image12_320 from '../assets/optimized/facial-female-three-quarter-8437-320.webp'
import image12_640 from '../assets/optimized/facial-female-three-quarter-8437-640.webp'
import image12_960 from '../assets/optimized/facial-female-three-quarter-8437-960.webp'
import image12_1200 from '../assets/optimized/facial-female-three-quarter-8437-1200.webp'
import original13 from '../assets/results/facial-male-front-7339.webp'
import image13_320 from '../assets/optimized/facial-male-front-7339-320.webp'
import image13_640 from '../assets/optimized/facial-male-front-7339-640.webp'
import image13_960 from '../assets/optimized/facial-male-front-7339-960.webp'
import image13_1200 from '../assets/optimized/facial-male-front-7339-1200.webp'
import original14 from '../assets/results/facial-male-front-8831.webp'
import image14_320 from '../assets/optimized/facial-male-front-8831-320.webp'
import image14_640 from '../assets/optimized/facial-male-front-8831-640.webp'
import image14_960 from '../assets/optimized/facial-male-front-8831-960.webp'
import image14_1200 from '../assets/optimized/facial-male-front-8831-1200.webp'
import original15 from '../assets/results/result-01-sem-data.webp'
import image15_320 from '../assets/optimized/result-01-sem-data-320.webp'
import image15_640 from '../assets/optimized/result-01-sem-data-640.webp'
import image15_960 from '../assets/optimized/result-01-sem-data-960.webp'
import image15_1200 from '../assets/optimized/result-01-sem-data-1200.webp'
import original16 from '../assets/results/result-02-sem-data.webp'
import image16_320 from '../assets/optimized/result-02-sem-data-320.webp'
import image16_640 from '../assets/optimized/result-02-sem-data-640.webp'
import image16_960 from '../assets/optimized/result-02-sem-data-960.webp'
import image16_1200 from '../assets/optimized/result-02-sem-data-1200.webp'
import original17 from '../assets/results/result-03-sem-data.webp'
import image17_320 from '../assets/optimized/result-03-sem-data-320.webp'
import image17_640 from '../assets/optimized/result-03-sem-data-640.webp'
import image17_960 from '../assets/optimized/result-03-sem-data-960.webp'
import image17_1200 from '../assets/optimized/result-03-sem-data-1200.webp'
import original18 from '../assets/results/result-10.jpg'
import image18_320 from '../assets/optimized/result-10-320.webp'
import image18_640 from '../assets/optimized/result-10-640.webp'
import image18_960 from '../assets/optimized/result-10-960.webp'
import image18_1200 from '../assets/optimized/result-10-1200.webp'
import original19 from '../assets/results/result-12.jpg'
import image19_320 from '../assets/optimized/result-12-320.webp'
import image19_640 from '../assets/optimized/result-12-640.webp'
import image19_960 from '../assets/optimized/result-12-960.webp'
import image19_1200 from '../assets/optimized/result-12-1200.webp'

export const specialtyImageProps = createImageProps({
  [original0]: { src: image0_1200, srcSet: `${image0_320} 320w, ${image0_640} 640w, ${image0_960} 960w, ${image0_1200} 1200w`, width: 1280, height: 1280 },
  [original1]: { src: image1_1100, srcSet: `${image1_320} 320w, ${image1_640} 640w, ${image1_960} 960w, ${image1_1100} 1100w`, width: 1100, height: 1467 },
  [original2]: { src: image2_1200, srcSet: `${image2_320} 320w, ${image2_640} 640w, ${image2_960} 960w, ${image2_1200} 1200w`, width: 1280, height: 1266 },
  [original3]: { src: image3_1200, srcSet: `${image3_320} 320w, ${image3_640} 640w, ${image3_960} 960w, ${image3_1200} 1200w`, width: 1280, height: 1280 },
  [original4]: { src: image4_1200, srcSet: `${image4_320} 320w, ${image4_640} 640w, ${image4_960} 960w, ${image4_1200} 1200w`, width: 1672, height: 941 },
  [original5]: { src: image5_960, srcSet: `${image5_320} 320w, ${image5_640} 640w, ${image5_960} 960w`, width: 960, height: 1280 },
  [original6]: { src: image6_853, srcSet: `${image6_320} 320w, ${image6_640} 640w, ${image6_853} 853w`, width: 853, height: 1280 },
  [original7]: { src: image7_1200, srcSet: `${image7_320} 320w, ${image7_640} 640w, ${image7_960} 960w, ${image7_1200} 1200w`, width: 1254, height: 1254 },
  [original8]: { src: image8_1200, srcSet: `${image8_320} 320w, ${image8_640} 640w, ${image8_960} 960w, ${image8_1200} 1200w`, width: 1400, height: 1867 },
  [original9]: { src: image9_1200, srcSet: `${image9_320} 320w, ${image9_640} 640w, ${image9_960} 960w, ${image9_1200} 1200w`, width: 1600, height: 1600 },
  [original10]: { src: image10_1200, srcSet: `${image10_320} 320w, ${image10_640} 640w, ${image10_960} 960w, ${image10_1200} 1200w`, width: 1600, height: 1600 },
  [original11]: { src: image11_1200, srcSet: `${image11_320} 320w, ${image11_640} 640w, ${image11_960} 960w, ${image11_1200} 1200w`, width: 1600, height: 1600 },
  [original12]: { src: image12_1200, srcSet: `${image12_320} 320w, ${image12_640} 640w, ${image12_960} 960w, ${image12_1200} 1200w`, width: 1600, height: 1600 },
  [original13]: { src: image13_1200, srcSet: `${image13_320} 320w, ${image13_640} 640w, ${image13_960} 960w, ${image13_1200} 1200w`, width: 1600, height: 1600 },
  [original14]: { src: image14_1200, srcSet: `${image14_320} 320w, ${image14_640} 640w, ${image14_960} 960w, ${image14_1200} 1200w`, width: 1600, height: 1452 },
  [original15]: { src: image15_1200, srcSet: `${image15_320} 320w, ${image15_640} 640w, ${image15_960} 960w, ${image15_1200} 1200w`, width: 1260, height: 780 },
  [original16]: { src: image16_1200, srcSet: `${image16_320} 320w, ${image16_640} 640w, ${image16_960} 960w, ${image16_1200} 1200w`, width: 1260, height: 780 },
  [original17]: { src: image17_1200, srcSet: `${image17_320} 320w, ${image17_640} 640w, ${image17_960} 960w, ${image17_1200} 1200w`, width: 1260, height: 780 },
  [original18]: { src: image18_1200, srcSet: `${image18_320} 320w, ${image18_640} 640w, ${image18_960} 960w, ${image18_1200} 1200w`, width: 1260, height: 780 },
  [original19]: { src: image19_1200, srcSet: `${image19_320} 320w, ${image19_640} 640w, ${image19_960} 960w, ${image19_1200} 1200w`, width: 1260, height: 780 },
})
